modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/Vonr/Ars-Polymorphia/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL = "https://github.com/Vonr/Ars-Polymorphia" #optional
logoFile="ars_polymorphia.png"
credits="Authors of Ars Nouveau and Polymorph"
authors = "${mod_authors}"

description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"


[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"


[[dependencies."${mod_id}"]]
modId="ars_nouveau"
type="required"
versionRange="${ars_version_range}"
ordering="AFTER"
side="BOTH"
    [dependencies."${mod_id}".mc-publish]
    modrinth = "ars-nouveau"
    curseforge = "ars-nouveau"


[[dependencies."${mod_id}"]]
modId="polymorph"
type="optional"
versionRange="${polymorph_version_range}"
ordering="AFTER"
side="BOTH"
    [dependencies."${mod_id}".mc-publish]
    modrinth = "polymorph"
    curseforge = "polymorph"